### ISSUE TITLE
add custom root folder during archival?

### ISSUE THREAD

**Issue by stephanos** [saracen/fastzip#28]
👋 I'm trying to compress a bunch of files and have everything inside a root folder (its name differs from the source directory).

So given
```
/tmp/source-dir
   /A.txt
   /B.txt
```
would create a ZIP file with a structure like this:
```
/myroot
   /A.txt
   /B.txt
```

I can't get the `myroot` root directory working without renaming the original source dir (not an option, unfortunately). I tried using symlinks (seems to compress symlink itself, not follow it?) and changing the file path in the `filepath.Walk` function (results in "file not found").

Is there a way to do this?

PS: I can't do this on the extract, since I have no control over that part

**Comment by saracen** [comment]
The only way to achieve this at the moment is by renaming the top-level directory on disk before archiving. Is that an option you have available to you in your environment?

**Comment by stephanos** [comment]
Thank you for your reply! I don't have that option right now, unfortunately. I'll probably fork fastzip and vendor it with my change for the time being. This is probably a very unique use case and I wouldn't expect support for it out-of-the-box necessarily, so I'll close the issue.
