### ISSUE TITLE
Prevent unnecessary directory in zip?

### ISSUE THREAD

**Issue by vedantroy** [saracen/fastzip#9]
When using fastzip, by default, there will be a single directory at the top level of the zip, which contains everything.

Is there a way to not have this top level directory?

**Comment by saracen** [comment]
@vedantroy It should be the case that files added are relative to the chroot directory passed to `NewArchiver`. 

If your chroot directory is a full path including the top level directory you're seeing, that should then ignore it.

Does that make sense? Let me know if that works.

**Comment by saracen** [comment]
@vedantroy Did you resolve your issue?

**Comment by vedantroy** [comment]
@saracen Yes, changing chroot fixed the issue.
